name: build and push docker image to docker hub
on:
  push:
    branches:
      - main


jobs:
  push_to_dockerhub:
    name: push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: False
          tags: |
            asslam1991/9antra:1.0.${{ github.run_number }}
            asslam1991/9antra:latest
