name: build and push docker image to docker hub
on:
  push:
    branches:
      - main


jobs:
  push_to_dockerhub:
    name: push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: False
          tags: |
            asslam1991/9antra:1.0.${{ github.run_number }}
            asslam1991/9antra:latest
      - name: Checkout argotest repo
        uses: actions/checkout@v4
        with:
          repository: 06061991/argocd
          token: ${{ secrets.GHCR_TOKEN }} # Crée un token PAT avec accès en écriture
          path: argocd
          ref: main

      - name: Update image tag in values.yaml
        run: |
          sed -i 's|tagfront: .*|tagfront: "1.0.${{ github.run_number }}"|' argocd/kantra-app/values.yaml


      - name: Commit and push changes to argocd
        run: |
          cd argocd
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kantra-app/values.yaml
          git commit -m "Update frontend image tag to 1.0.${{ github.run_number }}"
          git push

